spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:postgresql://postgres:5432/activitydb
    username: activity
    password: activity
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8080
